# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c716f52ea1d753310730c74c97b385740435bea9238e393394e09cbc84ecd68c3c419a9dcd51c0753cebc0708a917dce6aea879326d142a79b4a8e56ee0088c

test:
  secret_key_base: a64d32dcd1ec1f2a5933d77ac8143ce17865187ff02c8586e8f42f1ee82f60f8ada2088109a2c516c660cd2a8873afa4c520b4c2b74ce7542b21d3243d0681c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
